version: "3"

services:
  teamcity:
    image: jetbrains/teamcity-server
    restart: always
    ports:
      - "1979:8111"
    volumes:
      - ~/teamcity/data:/data/teamcity_server/datadir
      - ~/teamcity/logs:/opt/teamcity/logs
