unifi:
  image: "jacobalberty/unifi:latest"
  restart: always
  ports:
    - "8080:8080"
    - "8443:8443"
    - "3478:3478/udp"
    - "10001:10001/udp"
    - "6789:6789/tcp"
  mem_limit: 5130m
  environment:
    TZ: "America/New_York"
  volumes:
    - ~/unifi:/unifi
